 <nav id="menu">
    <ul>
        <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
        <li><a href="professor.php">HOME</a></li>
        <li><a href="agenda_prof.php">AGENDA</a></li>
        <li><a href="lancar_nota.php">LANÇAR NOTAS</a></li>
        <li><a href="consultar_nota.php">CONSULTAR NOTAS</a></li>
        <li><a href="lancar_orientacao.php">LANÇAR ORIENTAÇÃO</a></li>
        <li><a href="consultar_orientacao.php">CONSULTAR ORIENTAÇÃO</a></li>
        <li><a href="dados_cadastro.php">DADOS CADASTRAIS</a></li>
        
        <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
        <li> <?php echo $nome ?></li>
        <li><a href="../functions/logout.php">SAIR&nbsp;<img id="sair" src="../imagens/sair.png" width="20" height="20"></a></li>
        <hr>
    </ul>
    </nav>